spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:user_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

server:
  port: 8081

user-service:
  url: http://localhost:8081

notification-service:
  url: http://localhost:8083

cache:
  available-drivers-key: "available_drivers"

logging:
  level:
    com.taxi: DEBUG