# Запуск из каталога taxi-microservices: docker compose up --build
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - notification-service

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  trip-service:
    build:
      context: ./trip-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - user-service
      - notification-service
